Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/11/2022
Var
// Seção de Declarações das variáveis 
 a,b:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("PESO 80kg")
a<-80
escreval("ALTURA 1.8")
b<-1.8
escreva("IMC")
escreva(a/(b*b))

Fimalgoritmo