Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2022
Var
numero:inteiro
a:inteiro
Inicio
escreval("TENTE ACERTAR O NUMERO")
numero <- randi(10)

leia (a)
enquanto a<>numero faca
escreval ("VOCÊ ERROU, TENTE NOVAMENTE!")
leia (a)

fimenquanto
se a=numero entao
escreval("VOCÊ ACERTOU")
fimse
Fimalgoritmo