Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2022
Var
// Seção de Declarações das variáveis 
codigo:real

Inicio
escreval("ESCREVA A SENHA:")
leia(codigo)
enquanto codigo<>123456 faca
escreval("CÓDIGO INVÁLIDO")
escreval("ESCREVA NOVAMENTE")
leia(codigo)
fimenquanto
se codigo=123456 entao
escreval("CÓDIGO VÁLIDO")
fimse






Fimalgoritmo




